// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmvpoeryvuwkhnwfupet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtdnBvZXJ5dnV3a2hud2Z1cGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTgxODUsImV4cCI6MjA2NDczNDE4NX0.D8qdyUmsJtlW8451Tjt0ujr-v6eNL3mhzH50Y7_m9tA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);