// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://tqkhoiiqqwaywnsmdgva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxa2hvaWlxcXdheXduc21kZ3ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNzU2NjYsImV4cCI6MjA3Njg1MTY2Nn0.1W9TPZjR47_t_Y1I6ooujTM2Tb0nYe-9ZjIi4a04uvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);